# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild -scheme PagingMenuController -destination "generic/platform=iOS Simulator" CODE_SIGNING_ALLOWED=NO build | xcpretty -c
- set -o pipefail && xcodebuild -resolvePackageDependencies -project Example/PagingMenuControllerDemo.xcodeproj | xcpretty -c
- set -o pipefail && xcodebuild -project Example/PagingMenuControllerDemo.xcodeproj -scheme PagingMenuControllerDemo -destination "generic/platform=iOS Simulator" CODE_SIGNING_ALLOWED=NO build | xcpretty -c
- set -o pipefail && xcodebuild -project Example/PagingMenuControllerDemo.xcodeproj -scheme PagingMenuControllerDemo2 -destination "generic/platform=iOS Simulator" CODE_SIGNING_ALLOWED=NO build | xcpretty -c
